// export const TeamLogo = {
//     '국내축구': [
//         { name: '울산 HD FC', img: '/TeamLogoImages/K_LEAGUE/울산현대.png'  },
//         { name: '김천상무 FC', img: '/TeamLogoImages/K_LEAGUE/김천상무.png'},
//         { name: '강원 FC', img: '/TeamLogoImages/K_LEAGUE/강원FC.png'},
//         { name: '포항 노틸러스', img: '/TeamLogoImages/K_LEAGUE/포항스틸러스.png' },
//         { name: 'FC서울', img: '/TeamLogoImages/K_LEAGUE/FC서울.png' },
//         { name: '수원FC', img: '/TeamLogoImages/K_LEAGUE/수원FC.png' },
//         { name: '제주 유나이티드', img: '/TeamLogoImages/K_LEAGUE/제주유나이티드.png' },
//         { name: '대전 하나 시티즌', img: '/TeamLogoImages/K_LEAGUE/대전하나시티즌FC.png' },
//         { name: '광주 FC', img: '/TeamLogoImages/K_LEAGUE/광주FC.jpg' },
//         { name: '전북 현대 모터스', img: '/TeamLogoImages/K_LEAGUE/전북현대 모터스.png' },
//         { name: '대구FC', img: '/TeamLogoImages/K_LEAGUE/대구FC.png' },
//         { name: '인천 유나이티드', img: '/TeamLogoImages/K_LEAGUE/인천유나이티드.png' },
//     ],

//     '해외축구': [
//         { name: '레알 마드리드', img: '/TeamLogoImages/SUPER_LEAGUE/레알마드리드.png' },
//         { name: '리버풀', img: '/TeamLogoImages/SUPER_LEAGUE/리버풀.png' },
//         { name: '맨체스터 시티', img: '/TeamLogoImages/SUPER_LEAGUE/맨체스터시티.png' },
//         { name: '맨체스터\n유나이티드', img: '/TeamLogoImages/SUPER_LEAGUE/맨유.png' },
//         { name: '첼시', img: '/TeamLogoImages/SUPER_LEAGUE/첼시.png' },
//         { name: '토트넘', img: '/TeamLogoImages/SUPER_LEAGUE/토트넘.png' },    
//         { name: '바이에른 뮌헨', img: '/TeamLogoImages/SUPER_LEAGUE/뮌헨.png' },
//         { name: '유벤투스', img: '/TeamLogoImages/SUPER_LEAGUE/유벤투스.png' },
//         { name: 'AC밀란', img: '/TeamLogoImages/SUPER_LEAGUE/AC밀란.png' },
//         { name: '인터 밀란', img: '/TeamLogoImages/SUPER_LEAGUE/인터밀란.png' },
//         { name: 'PSG', img: '/TeamLogoImages/SUPER_LEAGUE/PSG.png' },
//         { name: '알 힐랄', img: '/TeamLogoImages/SUPER_LEAGUE/알힐랄SFC.png' },
//     ],
//     '국내야구': [
//         { name: 'LG', img: '/TeamLogoImages/KBO/LG트윈스.png' },
//         { name: 'KIA', img: '/TeamLogoImages/KBO/기아타이거즈.png' },
//         { name: '삼성', img: '/TeamLogoImages/KBO/삼성라이온즈.png' },
//         { name: '두산', img: '/TeamLogoImages/KBO/두산베어스.png' },
//         { name: 'SSG', img: '/TeamLogoImages/KBO/ssg랜더스.png' },
//         { name: 'KT', img: '/TeamLogoImages/KBO/kt위즈.png' },
//         { name: '롯데', img: '/TeamLogoImages/KBO/롯데자이언츠.png' },
//         { name: '한화', img: '/TeamLogoImages/KBO/한화이글스.png' },
//         { name: 'NC', img: '/TeamLogoImages/KBO/nc다이노스.png' },
//         { name: '키움', img: '/TeamLogoImages/KBO/키움히어로즈.png' },
//     ],
//     '여자배구': [
//         { name: '흥국생명', img: '/TeamLogoImages/V_LEAGUE/인천흥국생명핑크스파이더스.png' },
//         { name: '현대건설', img: '/TeamLogoImages/V_LEAGUE/수원현대건설힐스테이트.png' },
//         { name: 'IBK기업은행', img: '/TeamLogoImages/V_LEAGUE/화성IBK기업은행알토스.png' },
//         { name: '정관장', img: '/TeamLogoImages/V_LEAGUE/대전정관장레드스파크스.png' },
//         { name: '한국도로공사', img: '/TeamLogoImages/V_LEAGUE/김천한국도로공사하이패스.png' },
//         { name: '페퍼저축은행', img: '/TeamLogoImages/V_LEAGUE/광주페퍼저축은행AI페퍼스.png' },
//         { name: 'GS칼텍스', img: '/TeamLogoImages/V_LEAGUE/GS칼텍스서울KIXX.png' },
//     ],
//     'e스포츠': [
//         { name: 'T1', img: '/TeamLogoImages/LCK/티원.png' },
//         { name: '젠지', img: '/TeamLogoImages/LCK/젠지.png' },
//         { name: '한화', img: '/TeamLogoImages/LCK/한화생명e스포츠.png' },
//         { name: 'KT', img: '/TeamLogoImages/LCK/케이티롤스터.png' },
//         { name: '디플러스기아', img: '/TeamLogoImages/LCK/디플러스기아.png' },
//         { name: '광동', img: '/TeamLogoImages/LCK/광동프릭스.png' },
//         { name: '피어엑스', img: '/TeamLogoImages/LCK/비엔케이피어엑스.png' },
//         { name: '농심', img: '/TeamLogoImages/LCK/농심레드포스.png' },
//         { name: 'DRX', img: '/TeamLogoImages/LCK/디알엑스.png' },
//         { name: '브리온', img: '/TeamLogoImages/LCK/오케이저축은행브리온.png' },
//     ],

// };

export const TeamLogo = {
    '국내축구': [
        { name: '울산 HD FC', img: '/TeamLogoImages/K_LEAGUE/울산현대.png', hashtag: ['#울산'] },
        { name: '김천상무 FC', img: '/TeamLogoImages/K_LEAGUE/김천상무.png', hashtag: ['#김천상무'] },
        { name: '강원 FC', img: '/TeamLogoImages/K_LEAGUE/강원FC.png', hashtag: ['#강원FC'] },
        { name: '포항 노틸러스', img: '/TeamLogoImages/K_LEAGUE/포항스틸러스.png', hashtag: ['#포항노틸러스'] },
        { name: 'FC서울', img: '/TeamLogoImages/K_LEAGUE/FC서울.png', hashtag: ['#FC서울'] },
        { name: '수원FC', img: '/TeamLogoImages/K_LEAGUE/수원FC.png', hashtag: ['#수원FC'] },
        { name: '제주 유나이티드', img: '/TeamLogoImages/K_LEAGUE/제주유나이티드.png', hashtag: ['#제주유나이티드'] },
        { name: '대전 하나 시티즌', img: '/TeamLogoImages/K_LEAGUE/대전하나시티즌FC.png', hashtag: ['#대전하나시티즌'] },
        { name: '광주 FC', img: '/TeamLogoImages/K_LEAGUE/광주FC.jpg', hashtag: ['#광주FC'] },
        { name: '전북 현대 모터스', img: '/TeamLogoImages/K_LEAGUE/전북현대 모터스.png', hashtag: ['#전북현대모터스'] },
        { name: '대구FC', img: '/TeamLogoImages/K_LEAGUE/대구FC.png', hashtag: ['#대구FC'] },
        { name: '인천 유나이티드', img: '/TeamLogoImages/K_LEAGUE/인천유나이티드.png', hashtag: ['#인천유나이티드'] },
    ],

    '해외축구': [
        { name: '레알 마드리드', img: '/TeamLogoImages/SUPER_LEAGUE/레알마드리드.png', hashtag: ['#레알마드리드'] },
        { name: '리버풀', img: '/TeamLogoImages/SUPER_LEAGUE/리버풀.png', hashtag: ['#리버풀'] },
        { name: '맨체스터 시티', img: '/TeamLogoImages/SUPER_LEAGUE/맨체스터시티.png', hashtag: ['#맨시티'] },
        { name: '맨체스터 유나이티드', img: '/TeamLogoImages/SUPER_LEAGUE/맨유.png', hashtag: ['#맨유'] },
        { name: '첼시', img: '/TeamLogoImages/SUPER_LEAGUE/첼시.png', hashtag: ['#첼시'] },
        { name: '토트넘', img: '/TeamLogoImages/SUPER_LEAGUE/토트넘.png', hashtag: ['#토트넘'] },
        { name: '바이에른 뮌헨', img: '/TeamLogoImages/SUPER_LEAGUE/뮌헨.png', hashtag: ['#바이에른뮌헨'] },
        { name: '유벤투스', img: '/TeamLogoImages/SUPER_LEAGUE/유벤투스.png', hashtag: ['#유벤투스'] },
        { name: 'AC밀란', img: '/TeamLogoImages/SUPER_LEAGUE/AC밀란.png', hashtag: ['#AC밀란'] },
        { name: '인터 밀란', img: '/TeamLogoImages/SUPER_LEAGUE/인터밀란.png', hashtag: ['#인터밀란'] },
        { name: 'PSG', img: '/TeamLogoImages/SUPER_LEAGUE/PSG.png', hashtag: ['#PSG'] },
        { name: '알 힐랄', img: '/TeamLogoImages/SUPER_LEAGUE/알힐랄SFC.png', hashtag: ['#알힐랄'] },
    ],

    '국내야구': [
        { name: 'LG', img: '/TeamLogoImages/KBO/LG트윈스.png', hashtag: ['#LG트윈스'] },
        { name: 'KIA', img: '/TeamLogoImages/KBO/기아타이거즈.png', hashtag: ['#기아타이거즈'] },
        { name: '삼성', img: '/TeamLogoImages/KBO/삼성라이온즈.png', hashtag: ['#삼성라이온즈'] },
        { name: '두산', img: '/TeamLogoImages/KBO/두산베어스.png', hashtag: ['#두산베어스'] },
        { name: 'SSG', img: '/TeamLogoImages/KBO/ssg랜더스.png', hashtag: ['#SSG랜더스'] },
        { name: 'KT', img: '/TeamLogoImages/KBO/kt위즈.png', hashtag: ['#KT위즈'] },
        { name: '롯데', img: '/TeamLogoImages/KBO/롯데자이언츠.png', hashtag: ['#롯데자이언츠'] },
        { name: '한화', img: '/TeamLogoImages/KBO/한화이글스.png', hashtag: ['#한화이글스'] },
        { name: 'NC', img: '/TeamLogoImages/KBO/nc다이노스.png', hashtag: ['#NC다이노스'] },
        { name: '키움', img: '/TeamLogoImages/KBO/키움히어로즈.png', hashtag: ['#키움히어로즈'] },
    ],

    '여자배구': [
        { name: '흥국생명', img: '/TeamLogoImages/V_LEAGUE/인천흥국생명핑크스파이더스.png', hashtag: ['#흥국생명'] },
        { name: '현대건설', img: '/TeamLogoImages/V_LEAGUE/수원현대건설힐스테이트.png', hashtag: ['#현대건설'] },
        { name: 'IBK기업은행', img: '/TeamLogoImages/V_LEAGUE/화성IBK기업은행알토스.png', hashtag: ['#IBK기업은행'] },
        { name: '정관장', img: '/TeamLogoImages/V_LEAGUE/대전정관장레드스파크스.png', hashtag: ['#정관장'] },
        { name: '한국도로공사', img: '/TeamLogoImages/V_LEAGUE/김천한국도로공사하이패스.png', hashtag: ['#한국도로공사'] },
        { name: '페퍼저축은행', img: '/TeamLogoImages/V_LEAGUE/광주페퍼저축은행AI페퍼스.png', hashtag: ['#페퍼저축은행'] },
        { name: 'GS칼텍스', img: '/TeamLogoImages/V_LEAGUE/GS칼텍스서울KIXX.png', hashtag: ['#GS칼텍스'] },
    ],

    'e스포츠': [
        { name: 'T1', img: '/TeamLogoImages/LCK/티원.png', hashtag: ['#T1'] },
        { name: '젠지', img: '/TeamLogoImages/LCK/젠지.png', hashtag: ['#젠지'] },
        { name: '한화', img: '/TeamLogoImages/LCK/한화생명e스포츠.png', hashtag: ['#한화생명'] },
        { name: 'KT', img: '/TeamLogoImages/LCK/케이티롤스터.png', hashtag: ['#KT롤스터'] },
        { name: '디플러스기아', img: '/TeamLogoImages/LCK/디플러스기아.png', hashtag: ['#디플러스기아'] },
        { name: '광동', img: '/TeamLogoImages/LCK/광동프릭스.png', hashtag: ['#광동프릭스'] },
        { name: '피어엑스', img: '/TeamLogoImages/LCK/비엔케이피어엑스.png', hashtag: ['#피어엑스'] },
        { name: '농심', img: '/TeamLogoImages/LCK/농심레드포스.png', hashtag: ['#농심레드포스'] },
        { name: 'DRX', img: '/TeamLogoImages/LCK/디알엑스.png', hashtag: ['#DRX'] },
        { name: '브리온', img: '/TeamLogoImages/LCK/오케이저축은행브리온.png', hashtag: ['#브리온'] },
    ],
};
